{{/*
PVC metadata details to rendered on pvc resources or claim templates for statefulsets
*/}}
{{- define "aip.pvc.metadata" -}}
  {{- $context := .context | default $ -}}
  {{- $template := .template | default dict -}}
name: {{ .name }}
labels: {{- include "aip.labels.standard" $context | nindent 4 }}
  {{- $labels := $template.labels -}}
  {{- if $labels }}
  {{- include "aip.renderer" ( dict "value" $labels "context" $context ) | nindent 4 }}
  {{- end }}
annotations: {{- include "aip.annotations.basic" (dict "context" $context) | nindent 4 }}
  {{- $annotations := $template.annotations -}}
  {{- if $annotations }}
  {{- include "aip.renderer" (dict "value" $annotations "context" $context) | nindent 4 }}
  {{- end }}
{{- end -}}

{{/*
PVC spec details to rendered on pvc resources or claim templates for statefulsets
*/}}
{{- define "aip.pvc.spec" -}}
  {{- $context := .context | default $ -}}
  {{- $template := .template | default dict -}}
accessModes:
{{- range $template.accessModes }}
  - {{ . | quote }}
{{- end }}
resources:
  requests:
    storage: {{ $template.size | quote }}
{{- $storageClass := $template.storageClass -}}
{{- if $storageClass }}
storageClassName: {{ $storageClass }}
{{- end }}
{{- $volumeName := $template.volumeName -}}
{{- if $volumeName }}
volumeName: {{ $volumeName }}
{{- end }}
{{- end -}}
