validation:
   name         : RAID Semaphore validation
   description  : Simple validation for nInput_CBPMSemaphores and nInput_BPMSemaphores
   chSubscribe  : nattrmon::cvals
   waitForFinish: false
   execFrom     : nValidation_Generic
   execArgs     :
      checks:
         - attrPattern      : Semaphores  
           expr             : "'{{value}}' == 'red'"
           warnLevel        : HIGH
           warnTitleTemplate: "RED {{name}}"
           warnDescTemplate : "A RED semaphore for {{name}} was detected. This might stop RAID flows from running as expected. Please check more detail on <a href=\"http://allura.connectiv.local\">Allura</a>."
 
         - attrPattern      : Semaphores
           expr             : "'{{value}}' == 'yellow'"
           warnLevel        : LOW
           warnTitleTemplate: "Yellow {{name}}"
           warnDescTemplate : "A yellow semaphore for {{name}} was detected."
