sec: &SEC
  secFile  : /secrets/secrets.yaml
  secBucket: nattrmon

afpool: &AFPOOL
  max: 5
  min: 0
  #keepalive    : 60000   # 1 min
  #incrementsOf : 1
  #retry        : 3
  #retryInterval: 30000   # 30 sec

dbpool: &DBPOOL
  max: 10
  min: 0
  #keepalive    : 60000   # 1 min
  #incrementsOf : 1
  #retry        : 3
  #retryInterval: 30000   # 30 sec

input:
   name         : RAID Init
   cron         : "*/30 * * * * *"
   execFrom     : nInput_Init
   execArgs     :
     Kube:
       AF:
         # ------------------
         aipServers:      #"{{$path metadata.labels '[?key==`app.kubernetes.io/name`].value'}}"
         - key           : "{{metadata.name}}"
           <<            : *SEC
           secKey        : RAID
           timeout       : 100000
           conTimeOut    : 50000
           includeLatency: true
           pool          : *AFPOOL
           _kube         :
             namespace: "{{$env 'NAM_KUBE_NAMESPACE'}}"
             selector : &KUBE_SELECT
               where:
               - cond: match
                 args:
                 - "metadata.name"
                 - "{{$env 'NAM_KUBE_RAID'}}"
               - cond: equals
                 args:
                 - "status.phase"
                 - "Running"

       AFCache:
         # ------------------
         aipCache:     #"{{$path metadata.labels '[?key==`app.kubernetes.io/name`].value'}}"
         - key       : "{{metadata.name}}"
           ttl       : 5000
           _kube     :
             namespace: "{{$env 'NAM_KUBE_NAMESPACE'}}"
             selector : *KUBE_SELECT

     DB:
      dbServers:
      - key      : dbRAFMAdm
        <<       : *SEC
        secKey   : dbRAFM
        pool     : *DBPOOL
        timeout  : 30000

