input:
   name         : Failed flows retrieved from the database 
   #cron         : "5 */1 * * * *"
   #cron         : "* * * * * *"
   waitForFinish: true
   onlyOnEvent  : false
   timeout      : 60000
   timeInterval : 3560000
   execFrom     : nInput_DB
   execArgs     : 
      key : dbRAFMAdm
      sqlsByType:
         oracle:
            Database/Running Flows       : >
               SELECT INSTANCE_ID "Instance", 
                  C.SHORT_NAME "Flow", 
                  A.FLOW_VERSION "Version", 
                  A.FLOW_RUN_ID "RunID", 
                  A.CREATED_BY "User",
                  TO_CHAR(A.CREATED_DATE, 'YYYY-MM-DD HH24:MI:SS') "Flow Start Date", 
                  TRUNC((SYSDATE - A.CREATED_DATE)*24*60) "Flow Running Minutes", 
                  B.NAME "Task Name",
                  TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD HH24:MI:SS') "Task Start Date",
                  TRUNC((SYSDATE - B.CREATED_DATE)*24*60) "Task Running Minutes"
                  FROM CBPM_C_RUNNING_FLOWS A, CBPM_C_RUNNING_TASKS B, AF_T_OBJ_SPEC C 
                  WHERE A.FLOW_RUN_ID = B.FLOW_RUN_ID 
                  AND B.TASK_STATUS = 2
                  AND A.FLOW_STATUS = 2
                  AND C.OBJ_SPEC_UUID = A.FLOW_ID 
                  ORDER BY "Instance", "Flow Start Date" asc, "Task Start Date"
         
         postgresql:
            Database/Failed Flows last 1hour       : >
               SELECT coalesce(COUNT(1), 0) AS FAILED_COUNT FROM (
               SELECT "INSTANCE_ID" "Instance",
                  C."SHORT_NAME" "Flow",
                  A."FLOW_VERSION" "Version",
                  A."FLOW_RUN_ID" "RunID",
                  A."CREATED_BY" "User",
                  TO_CHAR(A."CREATED_DATE", 'YYYY-MM-DD HH24:MI:SS') "Flow Start Date",
                  DATE_PART('minute', CURRENT_DATE - A."CREATED_DATE") running_time
                  FROM "CBPM_C_RUNNING_FLOWS" A, "AF_T_OBJ_SPEC" C
                  WHERE A."FLOW_STATUS" = 3
                  AND C."OBJ_SPEC_UUID" = A."FLOW_ID"
                  AND  A."CREATED_DATE" > current_timestamp - interval '1 hour'
                ) t  
