input:
   name         : Engine wise Alarm Count retrieved from the database 
   #cron         : "*/11 * * * * *"
   waitForFinish: true
   onlyOnEvent  : false
   timeInterval : 660000
   timeout      : 60000
   execFrom     : nInput_DB
   execArgs     : 
      key : dbRAFMAdm
      sqlsByType:
         postgresql:
            Database/Engine wise Alarm Count  : >
                select a."NAME", coalesce (alert_count,0) alarm_count  from "FRAUD_V_ENGINE" a left join
                (select b."CREATED_BY", count(1) as alert_count  from "FRAUD_T_CASE" b where b."CREATED_DATE" > current_timestamp  - interval '15 minutes' group by b."CREATED_BY") b
                on a."NAME" = b."CREATED_BY"
                where a."NAME" like '%COR%' and (a."NAME"  like '%Subsc%' or a."NAME"  like  '%Offnet%')
