input:
   name         : Waiting File Count retrieved from the database 
   #cron         : "*/19 * * * * *"
   waitForFinish: true
   onlyOnEvent  : false
   timeout      : 60000
   timeInterval : 2000000
   execFrom     : nInput_DB
   execArgs     : 
      key : dbRAFMAdm
      sqlsByType:
         postgresql:
            Database/Waiting File Count  : >
                SELECT a."SHORT_NAME", coalesce(waiting_count,0) as waiting_count from "AF_T_OBJ_SPEC" a left join
                (select "STREAM_UUID", count(1) as waiting_count from "DP_C_INPUT" where
                "CREATED_DATE" > current_timestamp  - interval '1 day' and "STREAM_UUID" in
                ('74b44a4b-008f-4dd8-a03e-cb51191fbcc7', '12135f5b-2791-4b1b-adfd-b1824e3cb30a')
                and "STATUS"=0 group by  "STREAM_UUID") b on a."OBJ_SPEC_UUID" = b."STREAM_UUID"
                where a."OBJ_SPEC_UUID" in ('74b44a4b-008f-4dd8-a03e-cb51191fbcc7', '12135f5b-2791-4b1b-adfd-b1824e3cb30a')

