annotations:
  charts.openshift.io/archs: x86_64
  charts.openshift.io/name: RAID Revenue Assurance and Fraud Management
  charts.openshift.io/provider: Mobileum Inc.
  charts.openshift.io/supportURL: http://www.mobileum.com
apiVersion: v2
appVersion: 4.8.1
dependencies:
- name: aip-common
  repository: oci://162015117822.dkr.ecr.eu-west-1.amazonaws.com/aip-charts
  version: 0.13.0
description: RAFM backend product
keywords:
- rafm
kubeVersion: '>=1.16.0-0'
name: rafm
type: application
version: 4.8.1
