{{- if eq .Values.storage.type "s3" }}
  {{- if eq ( index .Values.storage.s3 "credentials-type") "static" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aip.names.fullname" . }}-secrets
  labels: {{- include "aip.labels.standard" . | nindent 4 }}
  annotations: {{- include "aip.annotations.standard" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
stringData:
    AWS_ACCESS_KEY_ID: {{ index .Values.storage.s3 "access-key-id" }}
    AWS_SECRET_ACCESS_KEY: {{ index .Values.storage.s3 "secret-access-key" }}
    {{- if ( index .Values.storage.s3 "session-token" ) }}
    AWS_SESSION_TOKEN: {{ index .Values.storage.s3 "session-token" }}
    {{- end }}
  {{- end }}
{{- end }}
