apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "aip.names.fullname" . }}-cfg
  annotations: {{- include "aip.annotations.standard" . | nindent 4 }}
  labels: {{- include "aip.labels.standard" . | nindent 4 }}
data:
  {{- if  .Values.cache.enabled }}
  KC_CACHE: "ispn"
  KC_CACHE_STACK: "kubernetes"
  JAVA_OPTS_APPEND: "-Djgroups.dns.query={{ include "aip.names.fullname" . }}-tcp.{{ .Release.Namespace }}.svc.cluster.local"
  CACHE_OWNERS_COUNT: '{{ .Values.config.replica_count }}'
  CACHE_OWNERS_AUTH_SESSIONS_COUNT: '{{ .Values.config.replica_count }}'
  {{- end }}
  KC_HOSTNAME_STRICT: "false"
  {{- if not (empty .Values.realm ) }}
  REALM_DETAILS: '{{ .Values.realm | toJson }}'
  {{- end }}
  {{- if .Values.tls.enabled }}
  # HTTPS mode flags
  KC_HTTPS_PORT: "8443"
  KC_HTTP_ENABLED: "false"
  KC_PROXY: "none"
  {{- else }}
  # HTTP mode flags
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_HOST: "0.0.0.0"
  KC_HTTP_PORT: "8080"
  KC_PROXY: "edge"
  KEYCLOAK_PROXY_ADDRESS_FORWARDING: "true"
  {{- end }}
  {{- if .Values.config.defaultTheme }}
  KC_SPI_THEME_DEFAULT: "{{ .Values.config.defaultTheme }}"
  {{- end }}
  {{- if .Values.db.dbMigration }}
  KC_UPGRADE_FLAG: "--spi-connections-jpa-legacy-migration-strategy=update"
  {{- end }}
  {{- if .Values.config.contextPath }}
  KC_HTTP_RELATIVE_PATH: "{{ .Values.config.contextPath }}"
  {{- end }}
  KC_LOG: "{{ .Values.config.log.options }}"
  KC_LOG_CONSOLE_OUTPUT: "{{ .Values.config.log.format }}"
  KC_LOG_FILE: "/opt/keycloak/data/log/keycloak.log"
  KC_LOG_FILE_OUTPUT: "{{ .Values.config.log.format }}"
  KC_LOG_LEVEL: "{{ .Values.config.log.level }}"
  {{- if .Values.tls.enabled }}
  KC_HTTPS_CERTIFICATE_FILE: "/opt/keycloak/conf/tls.crt"
  KC_HTTPS_CERTIFICATE_KEY_FILE: "/opt/keycloak/conf/tls.key"
  {{- end }}
  KC_DIR: "/opt/keycloak/data/export"
  KC_USERS: "realm_file"
  {{- if or (ne .Values.realmImport.configmap "") (ne .Values.realmImport.secret "") }}
  KC_FILE: "/opt/keycloak/data/import/realm-export.json"
  KC_OVERRIDE: "true"
  {{- end }}
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
  KC_FEATURES: "token-exchange"
