apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aip.names.fullname" . }}-kc-secrets
  annotations: {{- include "aip.annotations.standard" . | nindent 4 }}
  labels: {{- include "aip.labels.standard" . | nindent 4 }}
stringData:
  KEYCLOAK_ADMIN: {{ .Values.config.keycloak_user }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.config.keycloak_password }}