dataPersistence:
  enabled: false
  
persistence:
  common:
    - enabled: true
      name: shared
      mounts:
        - mountPath: /shared
      claim:
        accessModes:
          - ReadWriteOnce
        size: 5G
        storageClass: robin
        volumeName: 
        annotations:
          "helm.sh/hook": pre-install
          "helm.sh/hook-weight": "-9"
          "helm.sh/hook-delete-policy": before-hook-creation
 

permissions:
  common:
    - /shared   