############
# AIP 2.0.2 compatible
############

automountServiceAccountToken: false

skipSetup: true
deployment:
  name: "t80fm"
  waitOnFailure: true
  license:
    secretName: "fm-raid-license"
  productConfig:
    secretName: "t80fm-product-config"

image:

  #repository: "t80-rafm/rafm-8.2.7"
  #tag: "2.1.4"

  repository: "t80-rafm/rafm-8.2.10"
  #tag: "4.7.0"
  tag: "4.8.1"


tolerations:
- key: "node"
  operator: "Equal"
  value: "FMS"
  effect: "NoSchedule"

customPodLabels:
  cnfc_id: a3146b7b-ae37-464f-846f-2babdb5c25af

customPvcAnnotations:
  robin.io/replication: "2"
  robin.io/faultdomain: host
  robin.io/compression: LZ4
  robin.io/media: SSD


dataPersistence:
  enabled: false

persistence:
  common:
    - enabled: true
      name: product-shared
      mounts:
        - mountPath: /productShared
      claim:
        accessModes:
          - ReadWriteOnce
        size: 5G
        storageClass: robin
        volumeName:
        annotations:
          "helm.sh/hook": pre-install
          "helm.sh/hook-weight": "-9"
          "helm.sh/hook-delete-policy": before-hook-creation

    - enabled: true
      name: local
      mounts:
        - mountPath: /local
      claim:
        accessModes:
          - ReadWriteOnce
        size: 2G
        storageClass: robin
        volumeName:
        annotations:
          "helm.sh/hook": pre-install
          "helm.sh/hook-weight": "-9"
          "helm.sh/hook-delete-policy": before-hook-creations

    - enabled: true
      name: fms-loading-sat1-rafm
      mounts:
        - mountPath: /fms-loading-sat1-rafm
      claim:
        accessModes:
          - ReadWriteMany
        size: 1500G
        storageClass: robin
        volumeName:
        annotations:
          "helm.sh/hook": pre-install
          "helm.sh/hook-weight": "-9"
          "helm.sh/hook-delete-policy": before-hook-creations
          "robin.io/replication": "2"
          "robin.io/faultdomain": host
          "robin.io/compression": LZ4
          "robin.io/media": SSD 

permissions:
  common:
    - /productShared
    - /local
    
riskProduct:
  namespace: ns-mbl-raid-fm

  #Uncomment during the Installation
  #aipChart:  "aip/charts/rafm-2.1.4.tgz"

  #Uncomment the during the 8.2.10:4.7.0 upgrade
  #aipChart: "aip/charts/rafm-4.7.0.tgz"

  #Uncomment the during the 8.2.10:4.8.1 upgrade
  aipChart: "aip/charts/rafm-4.8.1.tgz"

  server: "common/aip_settings/resources/t80-resources.yaml"

  installPresentation: true

riskDatabase:
  namespace: t80-rafm
  deploymentName: postgresql-t80
  databaseName: rakuten
  tablespaceName: raiddata
  externalPort: 30480
