image:
  repository: "nattrmon"    
  tag: "0.8.10"

nattrmon:
  configMap: "nattrmont80-config-passive"
  secrets: "t80nattrmon-secrets"
  kubeMetrics: false
  podExec: false

customLabels:
  prometheus-scrape-interval: 15m

customPodLabels:
  ns_id: 144359a9-4da8-4867-8600-febf2407ab42
  cnf_id: 79b63e72-4153-420c-a320-d65072a5c018
  cnfc_id: 81d9d220-4070-4128-9bff-20ff2e2d7f75


resources:
  requests:
    memory: "256Mi"
    cpu: "2"
  limits:
    memory: "4Gi"
    cpu: "4"


customPodAnnotations:
  prometheus.io/path: "/metrics"
  prometheus.io/port: "8090"
  prometheus.io/scheme: "http"
  prometheus.io/scrape: "true"

automountServiceAccountToken: true

deployment:
  raidComponentPodName: "^[trs][0-9]{2}(?:[trsp][0-9]{2})*-?[a-zA-Z]*(?:-rafm)?-[0-9]+$"

service:
  type: "NodePort"

riskProduct:
  namespace: "ns-mbl-raif-fm"

  # Path to Helm Chart to be used for installation.
  # Located under risk-management packages directory
  aipChart: "aip/charts/nattrmon-0.8.10-DU.tgz"
  externalPort: 30300

