image:
  repository: aip/nattrmon
  registry: ""
  tag: 0.8.10
  pullPolicy: IfNotPresent
  pullSecrets: []

nattrmon:
  # true if necessary to include pod related metrics
  kubeMetrics: true
  # true if necessary to extract java GC related metrics by executing remote pod commands
  podExec    : true   # should be true, by default, because of inputs/15.javaGC.yaml to gather metrics from Portal
  # A configmap with a configs.zip composed of nattrmon's inputs, outputs and validations
  #configMap  : nattrmon-configs
  # The secrets necessary depending on the nattrmon configuration used
  #secrets    : nattrmon-secrets

deployment:
  port: 8090
  isPortal: false
  # Mask to query the RAID pods for the inputs related with RAID connection (example: PING)
  raidComponentPodName  : "^([a-zA-Z0-9]+-)?rafm-[0-9a-zA-Z]+$"
  # Namespace for RAID instances if diferent from the one nAttrMon is present.
  NAM_KUBE_RAID:
  # Plugs order for nAttrMon to load (default: "outputs,inputs,validations").
  PLUGSORDER: "outputs,inputs,validations"
  # Should nAttrMon execute in debug mode
  DEBUG: false
  # Java virtual mashine (JVM) for nAttrMon minimum memory to be used in percentage (default 50%)
  JVM_MEMMSPERC : "50.0"
  # Java virtual mashine (JVM) for nAttrMon maximum memory to be used in percentage (default 80%)
  JVM_MEMMXPERC : "80.0"
  # Java virtual mashine (JVM) for nAttrMon other parameters to be defined
  OAF_JARGS: ""
  # Comma-delimited list of OpenAF libraries to load
  LIBS: "s3.js"
  # Warning Notifications, location where the files should be stored, other than locally.
  CHANNEL_WNOTS:
    # if enabled set to false, locally will be used, if true then type and options must be set.
    enabled: false
    # Type of storage to be used (can be "s3" or "elasticsearch").
    type: ""
    options:
      # Secret Key to be used (in secrets.yaml file).
      secKey: ""
      # Secret bucket to be used (in secrets.yaml file).
      secBucket:  ""
      # Secret's file where the secrets for elastic search are kept.
      secFile: ""      
      #*******************************
      #  Options for s3 type
      #*******************************
      #  If set to true when updating and storing warnings, several files are kept (each warning will be kept in its file). If set to false, all warnings are kept in a single file.
      multifile: true
      #  The files are kept in gzip if set to true.
      gzip: true
      # ******************************
      # Options for elasticsearch type
      #*******************************
      # Index name to be used to store the warnings
      index: ""

service:
  port: 8090
  type: ClusterIP
  nodePort: ""
  ipFamilyPolicy: "SingleStack"
  ipFamilies: [ "IPv4" ]

resources:
  requests:
    memory: "256Mi"
    cpu: "2"
  limits:
    memory: "2048Mi"
    cpu: "4"

config:
  worker_count: 1

hostAliases: []
additionalCatalogs: {}

nodeAffinity: {}

podAffinity: {}

podAntiAffinity: {}

livenessProbe:
  path: "/livez"
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 30
  failureThreshold: 10
  successThreshold: 1

readinessProbe:
  path: "/healthz"
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 30
  failureThreshold: 10
  successThreshold: 1

# Necessary for nAttrMon to find other pods to retrieve metrics
automountServiceAccountToken: false

podSecurityContext:
  enabled: false

containerSecurityContext:
  enabled: true
  privileged: false
  allowPrivilegeEscalation: false

customPodLabels: {}

caTrust:
  enabled: false
  secret:
  configmap:

testAnnotation:
    "helm.sh/hook": test-success
    "helm.sh/hook-delete-policy": hook-succeeded