apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aip.names.fullname" . }}
  labels: {{- include "aip.labels.standard" . | nindent 4 }}
  annotations: {{- include "aip.annotations.standard" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.automountServiceAccountToken | default false }}