deployment:
  base-dir: "s3://mobileum/raidops/deployments/stage"

image:
  registry: "localhost:5000"

podSecurityContext:
  enabled: true
  fsGroupChangePolicy: OnRootMismatch  # Add this line (options: OnRootMismatch | Always)

volumePermissions:
  image:
    repository: "base"
    tag: "0.5.2"

    #repository: "base/base"
    #tag: "0.4.1"

#Valid values for storage.type: s3, gs
storage:
  type: s3
  endpoint: "http://127.0.0.1:30167"
  region: ""
  credentials-type: static
  access-key-id: "adm"
  secret-access-key: "Password1"


setup:
  resources:
    requests:
      cpu: "2000m"
      memory: "1Gi"
    limits:
      cpu: "4000m"
      memory: "6Gi"

process:
  resources:
    requests:
      cpu: "2000m"
      memory: "1Gi"
    limits:
      cpu: "4000m"
      memory: "6Gi"

        #cacerts:
        #configmap: cert-cfg-2
  
timezone: "UTC"

service:
  ipFamilies: [ "IPv4" ] 

riskProduct:

  # Path to license file, expected under "riskPackagesDir" directory
  license: "common/support_files/license.lic"
  helmInstallTimeout: 120m
  helmUpgradeTimeout: 30m
  podStartTimeout: 20
  adjustaipinstall: "false"
  adjustPVCDeclaration: "false"
  
  openShiftDeploy: false
  openShiftSettingsFile: common/aip_settings/openshift-settings.yaml

  storageS3SettingsFile: common/aip_settings/aws-s3-storage-settings.yaml
  storageGcSettingsFile: common/aip_settings/google-cloud-storage-settings.yaml

riskDatabase:
  createDatabase: false
  host: 172.20.128.3

  username: postgres
  password: postgres
  port: 5432

  version: "--version 11.9.13"
