volumePermissions:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ['ALL']
    runAsNonRoot: true
    seccompProfile:
      type: "RuntimeDefault"
    runAsUser: "auto"

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ['ALL']
  runAsNonRoot: true
  seccompProfile:
    type: "RuntimeDefault"


riskDatabase:
  bitnamiPostgreSQLSettings: "common/aip_settings/bitnami-postgresql-settings.yaml"
