apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: b761617ee1f95c2008e7085df4dfa9e61a13e24786af1e7a00c4b318822bf3fc
    cni.projectcalico.org/podIP: 240b:c0e0:205:547b:b474:2:0:7e3a/128
    cni.projectcalico.org/podIPs: 240b:c0e0:205:547b:b474:2:0:7e3a/128
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "calico",
          "ips": [
              "240b:c0e0:205:547b:b474:2:0:7e3a"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "calico",
          "ips": [
              "240b:c0e0:205:547b:b474:2:0:7e3a"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2025-09-04T07:47:58Z"
  generateName: keycloak-fc9cf5dd9-
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
    cnf_id: 79b63e72-4153-420c-a320-d65072a5c018
    cnfc_id: a5241d2a-de39-4538-99c6-ad835a8fa884
    ns_id: 144359a9-4da8-4867-8600-febf2407ab42
    pod-template-hash: fc9cf5dd9
  name: keycloak-fc9cf5dd9-z6d5w
  namespace: ns-mbl-raid-fm
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: keycloak-fc9cf5dd9
    uid: 7553173c-da86-4c21-a2d5-be291218cfee
  resourceVersion: "341662361"
  uid: 27ba7a4b-c5cc-417f-a86d-7b28fbe56288
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node
            operator: In
            values:
            - FMS
  automountServiceAccountToken: false
  containers:
  - env:
    - name: JAVA_OPTS
      value: -XX:InitialRAMPercentage=25.0 -XX:MaxRAMPercentage=90.0 -Djava.net.preferIPv4Stack=false
        -Djava.net.preferIPv6Addresses=true
    - name: TZ
      value: Asia/Tokyo
    - name: KC_HTTPS_REQUIRED
      value: none
    - name: KC_HTTP_ENABLED
      value: "true"
    - name: KC_PROXY
      value: edge
    envFrom:
    - configMapRef:
        name: keycloak-cfg
    - secretRef:
        name: keycloak-kc-secrets
    - secretRef:
        name: keycloak-db-secrets
    image: klstg-docker.slb-wartifactory-v.stg.rmn.local/mobileum/network-fraud-intelligence/keycloak:0.5.7
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /health/live
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 300
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 60
    name: keycloak-pod
    ports:
    - containerPort: 4444
      protocol: TCP
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 5
      httpGet:
        path: /health/ready
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 300
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 60
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /opt/keycloak/data/log/
      name: log-data
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  nodeName: uhn7kl5r7rbwk007.rmnkiba.local
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 0
  serviceAccount: keycloak-sa
  serviceAccountName: keycloak-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node
    operator: Equal
    value: FMS
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: log-data
    persistentVolumeClaim:
      claimName: keycloak-log
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-09-04T07:47:59Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-09-04T07:53:25Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-09-04T07:53:25Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-09-04T07:47:59Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: robin://ca896a18657cde659c930ef3edd2584f3d8f2fa11179c758ffd9c56245064a3e
    image: klstg-docker.slb-wartifactory-v.stg.rmn.local/mobileum/network-fraud-intelligence/keycloak:0.5.7
    imageID: docker-pullable://klstg-docker.slb-wartifactory-v.stg.rmn.local/mobileum/network-fraud-intelligence/keycloak@sha256:f4bb7a53c8414483921bfbeda806cc63a091f6e12575ee714169482982ae5848
    lastState: {}
    name: keycloak-pod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-09-04T07:48:15Z"
  hostIP: 240b:c0e0:105:547b:b473:2:7:0
  phase: Running
  podIP: 240b:c0e0:205:547b:b474:2:0:7e3a
  podIPs:
  - ip: 240b:c0e0:205:547b:b474:2:0:7e3a
  qosClass: Burstable
  startTime: "2025-09-04T07:47:59Z"
